### ISSUE TITLE
Noticing enable crashes on most recent chrome ext.

### ISSUE THREAD

**Issue by eselkin** [ccwalletio/tracker#82]
After awaiting a window.cardano.ccvault.isEnabled() and then awaiting a result from the window.cardano.ccvault.enabled(), I'm getting this error:

```bex-dom.js:2661 Uncaught (in promise) Error: no account set
    at checkResponseNoError (bex-dom.js:2935:23)
    at Object.enable (bex-dom.js:2744:9)
    at async <anonymous>:1:107```

Is the account supposed to be set somehow programmatically? I disabled the whitelisted site and re-enabled it to check if it's something about a new version needing a new authorization, but it didn't seem to make a difference.

**Comment by eselkin** [comment]
I failed to realize the DApp configuration on the settings menu
